### ISSUE TITLE
Issue with createUser(), returning 400

### ISSUE THREAD

**Issue by jwparktom** [mxenabled/mx-atrium-node#30]
Hello, I'm new to this API wrapper and I was testing out some basic endpoint functions and spotted an issue (which took a while to find):

While defining [ObjectSerializer.serialize()](https://github.com/mxenabled/mx-atrium-node/blob/master/atrium.js#L81), it seems that there was a tiny error that affects createUser() and maybe some other endpoint functions.

This:
```javascript
instance[attributeType.baseName] = ObjectSerializer.serialize(data[attributeType.name], attributeType.type);
```
Should be:
```javascript
instance[attributeType.baseName] = ObjectSerializer.serialize(data[attributeType.baseName], attributeType.type);
```

To match the parameter descriptions on the documentation. For example, on [Create User](https://atrium.mx.com/docs?javascript#create-user), the endpoint expects parameters with **underscores and NOT camelcase**. Since the error above sets the body to be empty, the final body will be `{user:{}}` instead of `{user:{is_disabled: false}}`. That, according to the doc, is not allowed and therefore the endpoint returns `status code 400`

Regards,
Tom

**Comment by jwparktom** [comment]
Looks like the issue can be solved this way too (not written on the doc, so that was a bit confusing):
```javascript
const user = new atrium.User();
user.metadata = "test metadata";
user.is_disabled = false;
``

Closing the issue.

**Comment by jwparktom** [comment]
That seems to work but does not actually solve the underscore and camel case issue. The above code will yield a request with `body: {user:{metadata:'test metadata'}}`, which shows that `ObjectSerializer.serialize()` disregards parameters with underscores.

**Comment by brettmortensen** [comment]
Thanks @jwparktom for reaching out. We are currently working on improving our libraries/docs and this feedback will help in that process.

The attribute "is_disabled" is camel case (isDisabled) in this library. Running the following code snippet with your api key and client id credentials should work.

```
var atrium = require('mx-atrium');

var client = new atrium.AtriumClient("YOUR MX API KEY", "YOUR MX CLIENT ID");

const user = new atrium.User();
user.metadata = "test metadata";
user.isDisabled = false;

const createRequestBody = new atrium.UserCreateRequestBody();
createRequestBody.user = user;

const response = client.users.createUser(createRequestBody);

response.then(function(value) {
  console.log(value);
});
```

**Comment by brettmortensen** [comment]
Closing issue for now, please let us know if anything comes up 👍
