### ISSUE TITLE
Missing types in ConnectWidgetRequestBody

### ISSUE THREAD

**Issue by tylercote** [mxenabled/mx-atrium-node#52]
Hello! I believe that the TypeScript types for 'color_scheme' and 'wait_for_full_aggregation' are missing from the ConnectWidgetRequestBody.

**Comment by brettmortensen** [comment]
Hey @tylercote, thanks for reaching out 👍 

I've just added these fields along with a few others in [this PR](https://github.com/mxenabled/mx-atrium-node/pull/53) and released as version 2.11.3 [here.](https://www.npmjs.com/package/mx-atrium)
